# 4.1 Introduction to Data Analysis with Pandas

In [1]:
# Pandas is a data manipulation and analysis tool that uses a data structure known as DataFrame. 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows & columns).
# Import Pandas Library into the current environment, note that "pd" is an alias of "Pandas" 

# Pandas offers several advantages: 
# 1. Pandas is superior at automating data processing tasks compared to Excel and can work with large amount of data.
# 2. It can handle large amount of missing data easily and efficiently. 
# 3. Pandas offers easy and powerful methods for data reshaping, pivoting, aggregating, merging, joining and concatenation.
# 4. Pandas offers multi-indexing capability of labels and can work well with time-series data
# 5. Comes with powerful Input/Output (IO) functions that allow for accessing Excel files and databases.

import pandas as pd

In [2]:
# Let's define a two-dimensional Pandas DataFrame from a python dictionary 
# We will use Pandas DataFrame constructor method "pd.DataFrame()" to create our Pandas DataFrame
# Data Source: https://statisticstimes.com/economy/projected-world-gdp-ranking.php

GDP_df = pd.DataFrame({'Country ID': ['USA', 'CHN' , 'IND', 'ARE', 'CAN', 'MEX'], 
                       'Country':['United States', 'China', 'India', 'United Arab Emirates', 'Canada', 'Mexico'], 
                       'GDP Per Capita [$]':[69375, 11891, 2116, 43538, 52791, 9967], 
                       'Global Rank':[5, 64, 150, 24, 15, 72]})
GDP_df

  Country ID               Country  GDP Per Capita [$]  Global Rank
0        USA         United States               69375            5
1        CHN                 China               11891           64
2        IND                 India                2116          150
3        ARE  United Arab Emirates               43538           24
4        CAN                Canada               52791           15
5        MEX                Mexico                9967           72

In [3]:
# Let's obtain the data type of this pandas DataFrame 
type(GDP_df)

pandas.core.frame.DataFrame

In [4]:
# Let's view the first couple of rows using ".head()" method
GDP_df.head(2)

  Country ID        Country  GDP Per Capita [$]  Global Rank
0        USA  United States               69375            5
1        CHN          China               11891           64

In [5]:
# Let's view the last couple of rows using ".tail()" method
GDP_df.tail(3)

  Country ID               Country  GDP Per Capita [$]  Global Rank
3        ARE  United Arab Emirates               43538           24
4        CAN                Canada               52791           15
5        MEX                Mexico                9967           72

In [6]:
# You can access a specific column in the Pandas DataFrame using the header name  
GDP_df['GDP Per Capita [$]']

0    69375
1    11891
2     2116
3    43538
4    52791
5     9967
Name: GDP Per Capita [$], dtype: int64

In [7]:
# Let's obtain a statistical summary about the DataFrame using the "describe()" method
GDP_df.describe()

       GDP Per Capita [$]  Global Rank
count             6.00000      6.00000
mean          31613.00000     55.00000
std           27365.16604     53.76988
min            2116.00000      5.00000
25%           10448.00000     17.25000
50%           27714.50000     44.00000
75%           50477.75000     70.00000
max           69375.00000    150.00000

In [8]:
# Obtain DataFrame information using the info() method
GDP_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country ID          6 non-null      object
 1   Country             6 non-null      object
 2   GDP Per Capita [$]  6 non-null      int64
 3   Global Rank         6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

# Exercise

In [9]:
# Stock prices obtained from Yahoo Finance as of Oct 17th, 2022
portfolio_df = pd.DataFrame({'company name': ['Alphabet', 'Netflix', 'Bank of America', 'Boeing', 'Apple'],
                             'stock ticker symbol':['GOOG', 'NFLX', 'BOA', 'BA', 'AAPL'],
                             'price per share [$]':[99, 245, 33, 136, 142],
                             'number of shares':[2, 7, 15, 30, 22]})
portfolio_df

      company name stock ticker symbol  price per share [$]  number of shares
0         Alphabet                GOOG                   99                 2
1          Netflix                NFLX                  245                 7
2  Bank of America                 BOA                   33                15
3           Boeing                  BA                  136                30
4            Apple                AAPL                  142                22

In [10]:
# Obtain a statistical summary
portfolio_df.describe()

       price per share [$]  number of shares
count             5.000000          5.000000
mean            131.000000         15.200000
std              77.087612         11.256109
min              33.000000          2.000000
25%              99.000000          7.000000
50%             136.000000         15.000000
75%             142.000000         22.000000
max             245.000000         30.000000

In [15]:
# Multiply the "price per share" by the "number of stocks"
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['number of shares']
stocks_dollar_value

0     198
1    1715
2     495
3    4080
4    3124
dtype: int64

In [12]:
# Sum up all values
stocks_dollar_value.sum()

9612

In [13]:
# Print the output
print('The total value of the portfolio = ${}'.format(stocks_dollar_value.sum()))

The total value of the portfolio = $9612

# 4.2 Handling Missing Data With pandas

In [1]:
# Pandas is a data manipulation and analysis tool that uses a data structure known as DataFrame. 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows & columns).
# Import Pandas Library into the current environment 
# "pd" is an alias of "Pandas" 
import pandas as pd

In [2]:
# Pandas is used to read a csv file and store data in a DataFrame
investor_df = pd.read_csv('investors_data.csv')
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [3]:
# Let's locate rows and columns that have Null values
# isnull() method returns a new DataFrame containing "True" in Null locations and "False" otherwise
investor_df.isnull()

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False
6,False,False,False,True,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False

In [4]:
# Let's see the total number of missing elements per column
investor_df.isnull().sum()

First Name                    0
Last Name                     0
Age                           0
Portfolio Size                1
Years with Investment Firm    1
Risk Tolerance                0
Goal                          0
dtype: int64

In [5]:
# Drop any row that contains a Null value 
# Note that the size of the dataframe has been reduced 
investor_df.dropna(how = 'any', inplace = True)

In [6]:
# Notice that rows 3 and 6 no longer exist!
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [7]:
# Let's check if we still have any missing values
investor_df.isnull().sum()

First Name                    0
Last Name                     0
Age                           0
Portfolio Size                0
Years with Investment Firm    0
Risk Tolerance                0
Goal                          0
dtype: int64

In [8]:
# Let's explore an alternative (smarter) method to deal with missing values
# Let's read the raw data again using Pandas as follows
investor_df = pd.read_csv('investors_data.csv')
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [9]:
# Let's obtain a statistical summary using "describe()" method
investor_df.describe()

             Age  Portfolio Size  Years with Investment Firm
count   9.000000        8.000000                    8.000000
mean   40.111111   353183.625000                   11.000000
std    11.634479   377372.061973                    9.561829
min    23.000000     1500.000000                    1.000000
25%    32.000000    70389.500000                    4.250000
50%    40.000000   225705.000000                    9.000000
75%    50.000000   525900.750000                   15.500000
max    55.000000   950000.000000                   30.000000

In [10]:
# Calculate the average portfolio size
investor_df['Portfolio Size'].mean()

353183.625

In [11]:
# You can use .fillna() to fill missing locations with a certain value
investor_df['Portfolio Size'].fillna(investor_df['Portfolio Size'].mean(), inplace = True)

In [12]:
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.000,5.0,aggressive,buy house
1,Sherif,George,54,950000.000,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.000,10.0,moderate,kids education
3,Victoria,Keller,43,300901.000,NaN,moderate,investment property
4,Sarah,Aly,26,41258.000,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.000,15.0,conservative,retire
6,Chris,Peter,38,353183.625,8.0,moderate,kids education
7,Nancy,Smith,55,900000.000,17.0,conservative,retire
8,Heidi,Smith,23,1500.000,1.0,moderate,retire early

# Exercise

In [13]:
# Read the data 
import pandas as pd 
investor_df = pd.read_csv('investors_data.csv')
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [14]:
# Let's locate rows that have Null values
investor_df.isnull().sum()

First Name                    0
Last Name                     0
Age                           0
Portfolio Size                1
Years with Investment Firm    1
Risk Tolerance                0
Goal                          0
dtype: int64

In [15]:
# Calculate the median value for "Years with Investment Firm" column
investor_df['Years with Investment Firm'].median()

9.0

In [16]:
# Use .fillna() method to fill a given column with a certain value
investor_df['Years with Investment Firm'].fillna(investor_df['Years with Investment Firm'].median(), inplace = True)

In [17]:
# Perform a sanity check
investor_df.isnull().sum()

First Name                    0
Last Name                     0
Age                           0
Portfolio Size                1
Years with Investment Firm    0
Risk Tolerance                0
Goal                          0
dtype: int64

In [18]:
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,9.0,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

# 4.3 DataFrame Filtering and Sorting

In [20]:
# Pandas is a data manipulation and analysis tool that uses a data structure known as DataFrame. 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows & columns).
# Import Pandas Library into the current environment 
# "pd" is an alias of "Pandas" 
import pandas as pd

In [21]:
# Pandas is used to read a csv file and store data in a DataFrame
investor_df = pd.read_csv('investors_data.csv')
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [22]:
# Select Loyal clients who have been with the investment firm for at least 15 years
loyal_df = investor_df[ investor_df['Years with Investment Firm'] >=15  ]
loyal_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
1,Sherif,George,54,950000.0,30.0,conservative,retire
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
7,Nancy,Smith,55,900000.0,17.0,conservative,retire

In [23]:
# You might need to reset the index for the new Pandas DataFrame
loyal_df.reset_index(inplace = True)
loyal_df

,index,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,1,Sherif,George,54,950000.0,30.0,conservative,retire
1,5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
2,7,Nancy,Smith,55,900000.0,17.0,conservative,retire

In [24]:
# You can sort the values in the dataframe according to the portfolio size
investor_df.sort_values(by = 'Portfolio Size')

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
1,Sherif,George,54,950000.0,30.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education

In [25]:
# Let's display the Pandas DataFrame again
# Notice that nothing has changed in memory! you have to make sure that inplace is set to True
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [26]:
# Set inplace = True to ensure that change has taken place in memory 
investor_df.sort_values(by = 'Portfolio Size', inplace = True)

In [28]:
# Note that now the change (ordering) took place 
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
1,Sherif,George,54,950000.0,30.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education

# Exercise

In [7]:
# Pandas is used to read a csv file and store data in a DataFrame
investor_df = pd.read_csv('investors_data.csv')
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [8]:
# Set inplace = True to ensure that change has taken place in memory 
investor_df.sort_values(by = 'Age', ascending = False, inplace = True)

In [9]:
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
1,Sherif,George,54,950000.0,30.0,conservative,retire
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
6,Chris,Peter,38,NaN,8.0,moderate,kids education
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [10]:
high_networth_df = investor_df[ investor_df['Portfolio Size'] >= 500000 ]
high_networth_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
1,Sherif,George,54,950000.0,30.0,conservative,retire

In [11]:
print('The combined portfolio size of clients with at least $500,000 is = ${}'.format(high_networth_df['Portfolio Size'].sum()))

The combined portfolio size of clients with at least $500,000 is = $1850000.0

# 4.4 pandas DataFrames and Functions

In [1]:
# Pandas is a data manipulation and analysis tool that uses a data structure known as DataFrame. 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows & columns).
# Import Pandas Library into the current environment 
# "pd" is an alias of "Pandas" 
import pandas as pd 
import numpy as np

In [2]:
# Pandas is used to read a csv file and store data in a DataFrame
investor_df = pd.read_csv('investors_data.csv')
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [3]:
# Define a function that increases the value of x by 10%
def portfolio_update(x):
    return x * 1.1 # assume that portfolio increased by 10%

In [4]:
# You can apply a function to the DataFrame column and add the results to a new column titled "Updated portfolio Size"
investor_df['Updated Portfolio Size'] = investor_df['Portfolio Size'].apply(portfolio_update)

In [5]:
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Updated Portfolio Size
0,Ryan,David,32,80100.0,5.0,aggressive,buy house,88110.0
1,Sherif,George,54,950000.0,30.0,conservative,retire,1045000.0
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education,165559.9
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property,330991.1
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans,45383.8
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire,441321.1
6,Chris,Peter,38,NaN,8.0,moderate,kids education,NaN
7,Nancy,Smith,55,900000.0,17.0,conservative,retire,990000.0
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early,1650.0

In [6]:
# You can also use Python built-in functions as well
investor_df['Sqrt Amount'] = investor_df['Age'].apply(np.sqrt)
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Updated Portfolio Size,Sqrt Amount
0,Ryan,David,32,80100.0,5.0,aggressive,buy house,88110.0,5.656854
1,Sherif,George,54,950000.0,30.0,conservative,retire,1045000.0,7.348469
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education,165559.9,6.324555
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property,330991.1,6.557439
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans,45383.8,5.099020
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire,441321.1,7.071068
6,Chris,Peter,38,NaN,8.0,moderate,kids education,NaN,6.164414
7,Nancy,Smith,55,900000.0,17.0,conservative,retire,990000.0,7.416198
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early,1650.0,4.795832

# Exercise

In [12]:
import pandas as pd
investor_df = pd.read_csv('investors_data.csv')
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,Ryan,David,32,80100.0,5.0,aggressive,buy house
1,Sherif,George,54,950000.0,30.0,conservative,retire
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire
6,Chris,Peter,38,NaN,8.0,moderate,kids education
7,Nancy,Smith,55,900000.0,17.0,conservative,retire
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early

In [13]:
def ranking(portfolio_size):
    if portfolio_size < 100000:
        return 'Low'
    elif portfolio_size < 500000:
        return 'Medium'
    else:
        return 'High'

In [14]:
investor_df['Rank'] = investor_df['Portfolio Size'].apply(ranking)
investor_df

,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Rank
0,Ryan,David,32,80100.0,5.0,aggressive,buy house,Low
1,Sherif,George,54,950000.0,30.0,conservative,retire,High
2,Sandra,Stevenson,40,150509.0,10.0,moderate,kids education,Medium
3,Victoria,Keller,43,300901.0,NaN,moderate,investment property,Medium
4,Sarah,Aly,26,41258.0,2.0,aggressive,pay student loans,Low
5,Bassel,Nasr,50,401201.0,15.0,conservative,retire,Medium
6,Chris,Peter,38,NaN,8.0,moderate,kids education,High
7,Nancy,Smith,55,900000.0,17.0,conservative,retire,High
8,Heidi,Smith,23,1500.0,1.0,moderate,retire early,Low

# 4.5 DataFrames Concatenation and Merging

In [1]:
# Pandas is a data manipulation and analysis tool that uses a data structure known as DataFrame. 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows & columns).
# Import Pandas Library into the current environment 
# "pd" is an alias of "Pandas" 
import pandas as pd

In [2]:
# Read the first excel sheet into a Pandas DataFrame
investor_1_df = pd.read_csv('investors_group_1.csv')
investor_1_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,A1,Ryan,David,32,80100,5,aggressive,buy house
1,A2,Sherif,George,54,950000,30,conservative,retire
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education
3,A4,Victoria,Keller,43,300901,3,moderate,investment property
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans
5,A6,Bassel,Nasr,50,401201,15,conservative,retire
6,A7,Chris,Peter,38,352000,8,moderate,kids education
7,A8,Nancy,Smith,55,900000,17,conservative,retire
8,A9,Heidi,Smith,23,1500,1,moderate,retire early

In [3]:
# Read the second excel sheet into a Pandas DataFrame
investor_2_df = pd.read_csv('investors_group_2.csv')
investor_2_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,B1,Paul,McDermid,31,70205,6,aggressive,buy house
1,B2,Steve,Mitchelle,55,990000,28,conservative,retire
2,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans
3,B4,Mohamed,Aly,43,38000,3,moderate,investment property
4,B5,Salma,Smith,22,3000,2,aggressive,pay student loans

In [4]:
# Let's concatenate both dataframes #1 and #2
investor_df_combined = pd.concat([investor_1_df, investor_2_df])
investor_df_combined

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,A1,Ryan,David,32,80100,5,aggressive,buy house
1,A2,Sherif,George,54,950000,30,conservative,retire
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education
3,A4,Victoria,Keller,43,300901,3,moderate,investment property
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans
5,A6,Bassel,Nasr,50,401201,15,conservative,retire
6,A7,Chris,Peter,38,352000,8,moderate,kids education
7,A8,Nancy,Smith,55,900000,17,conservative,retire
8,A9,Heidi,Smith,23,1500,1,moderate,retire early
0,B1,Paul,McDermid,31,70205,6,aggressive,buy house
1,B2,Steve,Mitchelle,55,990000,28,conservative,retire
2,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans
3,B4,Mohamed,Aly,43,38000,3,moderate,investment property
4,B5,Salma,Smith,22,3000,2,aggressive,pay student loans

In [5]:
# Note that index need to be reset, you can achieve this using df.reset_index()
# drop = True is used to drop the index column after reset_index() operation is performed
investor_df_combined.reset_index(drop = True)

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal
0,A1,Ryan,David,32,80100,5,aggressive,buy house
1,A2,Sherif,George,54,950000,30,conservative,retire
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education
3,A4,Victoria,Keller,43,300901,3,moderate,investment property
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans
5,A6,Bassel,Nasr,50,401201,15,conservative,retire
6,A7,Chris,Peter,38,352000,8,moderate,kids education
7,A8,Nancy,Smith,55,900000,17,conservative,retire
8,A9,Heidi,Smith,23,1500,1,moderate,retire early
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans

In [6]:
# Let's assume we acquired new information such as investors salaries and job titles
investor_new_df = pd.read_csv('investors_new_information.csv')
investor_new_df

   Investor ID  Salary             Job Title
0           A1   90000              engineer
1           A2  283000  engineering director
2           A3  150000       product manager
3           A4  175000        medical doctor
4           A5   75000                 nurse
5           A6  135000            Pharmacist
6           A7  125000               plumber
7           A8  198000        senior manager
8           A9   45000               teacher
9           B1   89000               manager
10          B2   25000       dental hygenist
11          B3  136000               dentist
12          B4  145000             professor
13          B5   35000   construction worker

In [7]:
# Let's merge data on 'Investor ID'
investor_df = pd.merge(investor_df_combined, investor_new_df, on = 'Investor ID')
investor_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker

# Exercise

In [8]:
new_client = {
        'Investor ID': ['C1'],
        'First Name': ['Ryan'], 
        'Last Name': ['Ahmed'],
        'Age': [33],
        'Portfolio Size': [30000],
        'Years with Investment Firm': [12],
        'Risk Tolerance': ['aggressive'],
        'Goal': ['retire early'],
        'Salary': [75000],
        'Job Title': ['professor']}
new_client_df = pd.DataFrame(new_client)
new_client_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,C1,Ryan,Ahmed,33,30000,12,aggressive,retire early,75000,professor

In [9]:
investor_df = pd.concat([investor_df, new_client_df], axis = 0)
investor_df

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker
0,C1,Ryan,Ahmed,33,30000,12,aggressive,retire early,75000,professor

In [10]:
# Note that index need to be reset, you can achieve this using df.reset_index()
investor_df.reset_index(drop = True)

,Investor ID,First Name,Last Name,Age,Portfolio Size,Years with Investment Firm,Risk Tolerance,Goal,Salary,Job Title
0,A1,Ryan,David,32,80100,5,aggressive,buy house,90000,engineer
1,A2,Sherif,George,54,950000,30,conservative,retire,283000,engineering director
2,A3,Sandra,Stevenson,40,150509,10,moderate,kids education,150000,product manager
3,A4,Victoria,Keller,43,300901,3,moderate,investment property,175000,medical doctor
4,A5,Sarah,Aly,26,41258,2,aggressive,pay student loans,75000,nurse
5,A6,Bassel,Nasr,50,401201,15,conservative,retire,135000,Pharmacist
6,A7,Chris,Peter,38,352000,8,moderate,kids education,125000,plumber
7,A8,Nancy,Smith,55,900000,17,conservative,retire,198000,senior manager
8,A9,Heidi,Smith,23,1500,1,moderate,retire early,45000,teacher
9,B1,Paul,McDermid,31,70205,6,aggressive,buy house,89000,manager
10,B2,Steve,Mitchelle,55,990000,28,conservative,retire,25000,dental hygenist
11,B3,Mirelle,Michael,39,160401,9,moderate,pay student loans,136000,dentist
12,B4,Mohamed,Aly,43,38000,3,moderate,investment property,145000,professor
13,B5,Salma,Smith,22,3000,2,aggressive,pay student loans,35000,construction worker
14,C1,Ryan,Ahmed,33,30000,12,aggressive,retire early,75000,professor

# 4.6 Get Financial Markets Data

In [1]:
# yfinance is an open-source tool used to get market data from Yahoo 
# Let's install the library
#!pip install yfinance
!pip install --user yfinance

# Let's import the library
import yfinance as yf 

# Pandas is used for dataframe and tabular data manipulation
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Collecting yfinance
  Downloading yfinance-0.2.37-py2.py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: numpy>=1.16.5 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (1.24.3)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (2.31.0)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: lxml>=4.9.1 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (4.9.3)
Requirement already satisfied: appdirs>=1.4.4 in c:\programdata\anaconda3\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from yfinance) (2023.3.post1)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.0.tar.gz (314 kB)
     ---------------------------------------- 0.0/314.6 kB ? eta -:--:--
     -------------------------------------- 314.6/314.6 kB 9.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.17.1.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ----------- ---------------------------- 0.9/3.0 MB 27.4 MB/s eta 0:00:01
     ----------------------- ---------------- 1.7/3.0 MB 27.7 MB/s eta 0:00:01
     ---------------------------------------  2.9/3.0 MB 23.5 MB/s eta 0:00:01
     ---------------------------------------- 3.0/3.0 MB 15.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from yfinance) (4.12.0)
Collecting html5lib>=1.1 (from yfinance)
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: six>=1.9 in c:\programdata\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sudhir kulaye\appdata\roaming\python\python311\site-packages (from requests>=2.31->yfinance) (2022.12.7)
Downloading yfinance-0.2.37-py2.py3-none-any.whl (72 kB)
   ---------------------------------------- 0.0/73.0 kB ? eta -:--:--
   ---------------------------------------- 73.0/73.0 kB 4.2 MB/s eta 0:00:00
Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Building wheels for collected packages: frozendict, peewee
  Building wheel for frozendict (pyproject.toml): started
  Building wheel for frozendict (pyproject.toml): finished with status 'done'
  Created wheel for frozendict: filename=frozendict-2.4.0-py3-none-any.whl size=15471 sha256=469c870d799e12ff84c0d613a49b98352077ebb4ef892f3639be68f9952ab669
  Stored in directory: c:\users\sudhir kulaye\appdata\local\pip\cache\wheels\31\dd\81\a814e6f8cde8a1bbc1f088fdc273943371f10478b91a605e14
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.17.1-py3-none-any.whl size=136948 sha256=85ada80ecb81dc9940a2a0a3c82845577c69c40d025a0f656cb78337e8641d6e
  Stored in directory: c:\users\sudhir kulaye\appdata\local\pip\cache\wheels\33\d2\ca\79b9807826bc7ef0b86a1ee28c372daaf073f9aa8756eedd7f
Successfully built frozendict peewee
Installing collected packages: peewee, multitasking, html5lib, frozendict, yfinance
Successfully installed frozendict-2.4.0 html5lib-1.1 multitasking-0.0.11 peewee-3.17.1 yfinance-0.2.37

  WARNING: The script sample.exe is installed in 'C:\Users\Sudhir Kulaye\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Using Yahoo Finance tool to fetch all data related to stock of interest
# Note that data is obtained in an object, we can then apply methods to get specific data from the object
# Note that the output is returned in a Python dictionary
stock = yf.Ticker("AAPL")
stock

yfinance.Ticker object <AAPL>

In [3]:
# Let's explore some available methods, add a period "." and then click "tab" to display all available methods
# Note that actions indicate dividends and stock splits
# Recommendations indicate analyst's ratings
# Analysis indicates EPS targets 
# Info returns company information in a dictionary format
stock.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '408 996 1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 161000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 62,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'totalPay': 16239562,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Luca  Maestri',
   'age': 60,
   'title': 'CFO & Senior VP',
   'yearBorn': 1963,
   'fiscalYear': 2023,
   'totalPay': 4612242,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Jeffrey E. Williams',
   'age': 59,
   'title': 'Chief Operating Officer',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4637585,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 59,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 4618064,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 56,
   'title': 'Senior Vice President of Retail',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 4613369,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris  Kondo',
   'title': 'Senior Director of Corporate Accounting',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James  Wilson',
   'title': 'Chief Technology Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 49,
   'title': 'Head of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 5,
 'boardRisk': 1,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1709251200,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 173.31,
 'open': 171.7,
 'dayLow': 170.51,
 'dayHigh': 172.23,
 'regularMarketPreviousClose': 173.31,
 'regularMarketOpen': 171.7,
 'regularMarketDayLow': 170.51,
 'regularMarketDayHigh': 172.23,
 'dividendRate': 0.96,
 'dividendYield': 0.0056,
 'exDividendDate': 1707436800,
 'payoutRatio': 0.14770001,
 'fiveYearAvgDividendYield': 0.74,
 'beta': 1.289,
 'trailingPE': 26.668741,
 'forwardPE': 23.94972,
 'volume': 64574490,
 'regularMarketVolume': 64574490,
 'averageVolume': 61993919,
 'averageVolume10days': 72081780,
 'averageDailyVolume10Day': 72081780,
 'marketCap': 2647976837120,
 'fiftyTwoWeekLow': 159.78,
 'fiftyTwoWeekHigh': 199.62,
 'priceToSalesTrailing12Months': 6.8652725,
 'fiftyDayAverage': 181.2792,
 'twoHundredDayAverage': 183.52095,
 'trailingAnnualDividendRate': 0.95,
 'trailingAnnualDividendYield': 0.005481507,
 'currency': 'USD',
 'enterpriseValue': 2682913816576,
 'profitMargins': 0.26163,
 'floatShares': 15414548871,
 'sharesOutstanding': 15441899520,
 'sharesShort': 110863064,
 'sharesShortPriorMonth': 97665956,
 'sharesShortPreviousMonthDate': 1707955200,
 'dateShortInterest': 1710460800,
 'sharesPercentSharesOut': 0.0072000003,
 'heldPercentInsiders': 0.059359998,
 'heldPercentInstitutions': 0.56711,
 'shortRatio': 1.64,
 'shortPercentOfFloat': 0.0072000003,
 'impliedSharesOutstanding': 15615699968,
 'bookValue': 4.793,
 'priceToBook': 35.777172,
 'lastFiscalYearEnd': 1696032000,
 'nextFiscalYearEnd': 1727654400,
 'mostRecentQuarter': 1703894400,
 'earningsQuarterlyGrowth': 0.131,
 'netIncomeToCommon': 100912996352,
 'trailingEps': 6.43,
 'forwardEps': 7.16,
 'pegRatio': 2.38,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 6.956,
 'enterpriseToEbitda': 20.621,
 '52WeekChange': 0.031955242,
 'SandP52WeekChange': 0.27393317,
 'lastDividendValue': 0.24,
 'lastDividendDate': 1707436800,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'AAPL',
 'underlyingSymbol': 'AAPL',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'firstTradeDateEpochUtc': 345479400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '8b10e4ae-9eeb-3684-921a-9ab27e4d87aa',
 'messageBoardId': 'finmb_24937',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 171.48,
 'targetHighPrice': 250.0,
 'targetLowPrice': 158.0,
 'targetMeanPrice': 200.52,
 'targetMedianPrice': 200.0,
 'recommendationMean': 2.2,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 39,
 'totalCash': 73100001280,
 'totalCashPerShare': 4.734,
 'ebitda': 130108997632,
 'totalDebt': 108040003584,
 'quickRatio': 0.92,
 'currentRatio': 1.073,
 'totalRevenue': 385706000384,
 'debtToEquity': 145.803,
 'revenuePerShare': 24.648,
 'returnOnAssets': 0.21181,
 'returnOnEquity': 1.5426899,
 'freeCashflow': 86563127296,
 'operatingCashflow': 116433002496,
 'earningsGrowth': 0.16,
 'revenueGrowth': 0.021,
 'grossMargins': 0.45027,
 'ebitdaMargins': 0.33733,
 'operatingMargins': 0.33764,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.1108}

In [4]:
# Let's obtain the company beta
# Remember that Beta is a measure of the security volatility compared to the market (S&P 500) 
# Stocks with betas greater than 1.0 are more volatile compared to S&P 500 
print("The company beta is = {}".format(stock.info['beta']))

The company beta is = 1.289

In [5]:
# Let's obtain the company's free cash flow (FCF)  
# Free cash flow is the cash left in a company after it pays for its operating and capital expenditures.
print("The company cash is = ${}".format(stock.info['freeCashflow']))

The company cash is = $86563127296

In [6]:
# Let's obtain the Price-to-Earnings (P/E) Ratio 
# Price-to-Earnings (P/E) ratio is calculated by dividing the current share price by its earnings per share (EPS) 
# High price-to-earnings ratio could indicate that the company's stock is overvalued 
# Example: S&P500 P/E ratio ranged from 5x in 1917 to 120x in 2009 right before the financial crisis 
# Trailing P/E is calculated using past performance by dividing the current stock price by total EPS earnings over the past 12 months.
print("The company Price-to-Earnings (P/E) ratio is = {} ".format(stock.info['trailingPE']))

The company Price-to-Earnings (P/E) ratio is = 26.668741

In [7]:
# You can also obtain cash flow statements
stock.get_cashflow()

,2023-09-30,2022-09-30,2021-09-30,2020-09-30
FreeCashFlow,99584000000.0,111443000000.0,92953000000.0,73365000000.0
RepurchaseOfCapitalStock,-77550000000.0,-89402000000.0,-85971000000.0,-72358000000.0
RepaymentOfDebt,-11151000000.0,-9543000000.0,-8750000000.0,-12629000000.0
IssuanceOfDebt,5228000000.0,5465000000.0,20393000000.0,16091000000.0
IssuanceOfCapitalStock,NaN,NaN,1105000000.0,880000000.0
CapitalExpenditure,-10959000000.0,-10708000000.0,-11085000000.0,-7309000000.0
InterestPaidSupplementalData,3803000000.0,2865000000.0,2687000000.0,3002000000.0
IncomeTaxPaidSupplementalData,18679000000.0,19573000000.0,25385000000.0,9501000000.0
EndCashPosition,30737000000.0,24977000000.0,35929000000.0,39789000000.0
BeginningCashPosition,24977000000.0,35929000000.0,39789000000.0,50224000000.0
ChangesInCash,5760000000.0,-10952000000.0,-3860000000.0,-10435000000.0
FinancingCashFlow,-108488000000.0,-110749000000.0,-93353000000.0,-86820000000.0
CashFlowFromContinuingFinancingActivities,-108488000000.0,-110749000000.0,-93353000000.0,-86820000000.0
NetOtherFinancingCharges,-6012000000.0,-6383000000.0,-5580000000.0,-2880000000.0
CashDividendsPaid,-15025000000.0,-14841000000.0,-14467000000.0,-14081000000.0
CommonStockDividendPaid,-15025000000.0,-14841000000.0,-14467000000.0,-14081000000.0
NetCommonStockIssuance,-77550000000.0,-89402000000.0,-85971000000.0,-72358000000.0
CommonStockPayments,-77550000000.0,-89402000000.0,-85971000000.0,-72358000000.0
CommonStockIssuance,NaN,NaN,1105000000.0,880000000.0
NetIssuancePaymentsOfDebt,-9901000000.0,-123000000.0,12665000000.0,2499000000.0
NetShortTermDebtIssuance,-3978000000.0,3955000000.0,1022000000.0,-963000000.0
NetLongTermDebtIssuance,-5923000000.0,-4078000000.0,11643000000.0,3462000000.0
LongTermDebtPayments,-11151000000.0,-9543000000.0,-8750000000.0,-12629000000.0
LongTermDebtIssuance,5228000000.0,5465000000.0,20393000000.0,16091000000.0
InvestingCashFlow,3705000000.0,-22354000000.0,-14545000000.0,-4289000000.0
CashFlowFromContinuingInvestingActivities,3705000000.0,-22354000000.0,-14545000000.0,-4289000000.0
NetOtherInvestingChanges,-1337000000.0,-2086000000.0,-385000000.0,-909000000.0
NetInvestmentPurchaseAndSale,16001000000.0,-9560000000.0,-3075000000.0,5453000000.0
SaleOfInvestment,45514000000.0,67363000000.0,106483000000.0,120391000000.0
PurchaseOfInvestment,-29513000000.0,-76923000000.0,-109558000000.0,-114938000000.0
NetBusinessPurchaseAndSale,NaN,-306000000.0,-33000000.0,-1524000000.0
PurchaseOfBusiness,NaN,-306000000.0,-33000000.0,-1524000000.0
NetPPEPurchaseAndSale,-10959000000.0,-10708000000.0,-11085000000.0,-7309000000.0
PurchaseOfPPE,-10959000000.0,-10708000000.0,-11085000000.0,-7309000000.0
OperatingCashFlow,110543000000.0,122151000000.0,104038000000.0,80674000000.0
CashFlowFromContinuingOperatingActivities,110543000000.0,122151000000.0,104038000000.0,80674000000.0
ChangeInWorkingCapital,-6577000000.0,1200000000.0,-4911000000.0,5690000000.0
ChangeInOtherWorkingCapital,NaN,478000000.0,1676000000.0,2081000000.0
ChangeInOtherCurrentLiabilities,3031000000.0,6110000000.0,7475000000.0,8916000000.0
ChangeInOtherCurrentAssets,-5684000000.0,-6499000000.0,-8042000000.0,-9588000000.0
ChangeInPayablesAndAccruedExpense,-1889000000.0,9448000000.0,12326000000.0,-4062000000.0
ChangeInPayable,-1889000000.0,9448000000.0,12326000000.0,-4062000000.0
ChangeInAccountPayable,-1889000000.0,9448000000.0,12326000000.0,-4062000000.0
ChangeInInventory,-1618000000.0,1484000000.0,-2642000000.0,-127000000.0
ChangeInReceivables,-417000000.0,-9343000000.0,-14028000000.0,8470000000.0
ChangesInAccountReceivables,-1688000000.0,-1823000000.0,-10125000000.0,6917000000.0
OtherNonCashItems,-2227000000.0,1006000000.0,-4921000000.0,-97000000.0
StockBasedCompensation,10833000000.0,9038000000.0,7906000000.0,6829000000.0
DeferredTax,NaN,895000000.0,-4774000000.0,-215000000.0
DeferredIncomeTax,NaN,895000000.0,-4774000000.0,-215000000.0
DepreciationAmortizationDepletion,11519000000.0,11104000000.0,11284000000.0,11056000000.0
DepreciationAndAmortization,11519000000.0,11104000000.0,11284000000.0,11056000000.0
NetIncomeFromContinuingOperations,96995000000.0,99803000000.0,94680000000.0,57411000000.0

In [8]:
# Let's view some recommendations
stock.recommendations.tail(20)

  period  strongBuy  buy  hold  sell  strongSell
0     0m         11   21     6     0           0
1    -1m         10   17    12     2           0
2    -2m         10   17    12     2           0
3    -3m         10   24     7     1           0

In [9]:
# Using Yahoo Finance tool to fetch stock data
# Actions is used to obtain dividends and stock splits 
dividends_splits_df = stock.actions
dividends_splits_df

                           Dividends  Stock Splits
Date
1987-05-11 00:00:00-04:00   0.000536           0.0
1987-06-16 00:00:00-04:00   0.000000           2.0
1987-08-10 00:00:00-04:00   0.000536           0.0
1987-11-17 00:00:00-05:00   0.000714           0.0
1988-02-12 00:00:00-05:00   0.000714           0.0
...                              ...           ...
2023-02-10 00:00:00-05:00   0.230000           0.0
2023-05-12 00:00:00-04:00   0.240000           0.0
2023-08-11 00:00:00-04:00   0.240000           0.0
2023-11-10 00:00:00-05:00   0.240000           0.0
2024-02-09 00:00:00-05:00   0.240000           0.0

[87 rows x 2 columns]

In [10]:
# Let's obtain the balance sheet for Apple
balance_df = stock.get_balance_sheet()
balance_df.round()

,2023-09-30,2022-09-30,2021-09-30,2020-09-30
TreasurySharesNumber,0.0,NaN,NaN,NaN
OrdinarySharesNumber,15550061000.0,15943425000.0,16426786000.0,16976763000.0
ShareIssued,15550061000.0,15943425000.0,16426786000.0,16976763000.0
NetDebt,81123000000.0,96423000000.0,89779000000.0,74420000000.0
TotalDebt,111088000000.0,120069000000.0,124719000000.0,112436000000.0
...,...,...,...,...
CashCashEquivalentsAndShortTermInvestments,61555000000.0,48304000000.0,62639000000.0,90943000000.0
OtherShortTermInvestments,31590000000.0,24658000000.0,27699000000.0,52927000000.0
CashAndCashEquivalents,29965000000.0,23646000000.0,34940000000.0,38016000000.0
CashEquivalents,1606000000.0,5100000000.0,17635000000.0,20243000000.0
CashFinancial,28359000000.0,18546000000.0,17305000000.0,17773000000.0

In [11]:
# Let's import datetime package 
import datetime
 
# Specify the starting date 
startDate = datetime.datetime(2021, 3, 1)
 
# Specify the end date 
endDate = datetime.datetime(2022, 3, 1)
 
# Obtain the stock price data
print(stock.history(start = startDate, end = endDate))

                                 Open        High         Low       Close  \
Date
2021-03-01 00:00:00-05:00  121.628893  125.737247  120.685349  125.599648
2021-03-02 00:00:00-05:00  126.209028  126.513712  122.867303  122.975418
2021-03-03 00:00:00-05:00  122.670722  123.555297  119.751627  119.967857
2021-03-04 00:00:00-05:00  119.663166  121.481455  116.586818  118.070930
2021-03-05 00:00:00-05:00  118.906376  119.849920  115.554821  119.338829
...                               ...         ...         ...         ...
2022-02-22 00:00:00-05:00  163.115971  164.806658  160.317944  162.463440
2022-02-23 00:00:00-05:00  163.669627  164.272735  157.945052  158.261444
2022-02-24 00:00:00-05:00  150.856066  161.010033  150.282617  160.901276
2022-02-25 00:00:00-05:00  161.988829  163.254365  159.052384  162.987427
2022-02-28 00:00:00-05:00  161.217657  163.550993  160.594770  163.254379

                              Volume  Dividends  Stock Splits
Date
2021-03-01 00:00:00-05:00  116307900        0.0           0.0
2021-03-02 00:00:00-05:00  102260900        0.0           0.0
2021-03-03 00:00:00-05:00  112966300        0.0           0.0
2021-03-04 00:00:00-05:00  178155000        0.0           0.0
2021-03-05 00:00:00-05:00  153766600        0.0           0.0
...                              ...        ...           ...
2022-02-22 00:00:00-05:00   91162800        0.0           0.0
2022-02-23 00:00:00-05:00   90009200        0.0           0.0
2022-02-24 00:00:00-05:00  141147500        0.0           0.0
2022-02-25 00:00:00-05:00   91974200        0.0           0.0
2022-02-28 00:00:00-05:00   95056600        0.0           0.0

[253 rows x 7 columns]

# Exercise

In [4]:
# Let's import the library
import yfinance as yf 

# Pandas is used for dataframe and tabular data manipulation
import pandas as pd

In [5]:
stock = yf.Ticker("TCS.NS")
stock.info

{'address1': 'TCS House',
 'address2': 'Raveline Street Fort',
 'city': 'Mumbai',
 'zip': '400001',
 'country': 'India',
 'phone': '91 22 6778 9595',
 'website': 'https://www.tcs.com',
 'industry': 'Information Technology Services',
 'industryKey': 'information-technology-services',
 'industryDisp': 'Information Technology Services',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Tata Consultancy Services Limited provides information technology (IT) and IT enabled services worldwide. It operates through Banking, Financial Services and Insurance; Manufacturing; Retail and Consumer Business; Communication, Media and Technology; Life Sciences and Healthcare; and Others segments. The company provides TCS ADD, a suite of technology platforms for clinical research and drug development; TCS BaNCS, a financial solution platform; TCS BFSI Platforms, a cloud-native, as-a-service that helps FIs and insurance firms; TCS CHROMA, a cloud-based talent management solution; customer intelligence and insight solutions; TCS ERP on Cloud, a hosted ERP applications and services platform; TCS HOBS, a connected devices management platform; and ignio, an autonomous enterprise software. It also offers TCS Intelligent Urban Exchange, smart cities and enterprises solution; TCS OmniStore, a commerce platform; TCS OPTUMERA, a retail-connected strategic intelligence platform; TCS TAP, a procurement offering; TCS MasterCraft, a platform of intelligent automation products; Quartz- the Smart Ledgers, a blockchain solution; Jile, an enterprise agile planning and delivery tool; TCS iON, an IT-as-a-Service model that provides business solutions; and TCS TwinX, an enterprise digital twin platform. In addition, the company provides cloud, cognitive business, consulting, cybersecurity, data and analytics, enterprise solutions, Internet of Things and digital engineering, TCS interactive, and sustainability services. It serves capital markets; communications, media, and information services; public services; energy, resource, and utility industries; consumer goods and distribution industries; and banking, education, healthcare, high tech, insurance, life science, manufacturing, retail, travel, and logistics industries. The company was founded in 1968 and is headquartered in Mumbai, India. Tata Consultancy Services Limited is a subsidiary of Tata Sons Private Limited.',
 'fullTimeEmployees': 603305,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Ganapathy Subramaniam Natarajan M.Sc.',
   'age': 64,
   'title': 'COO & Non-Independent Executive Director',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'totalPay': 236020000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. K.  Krithivasan B.E, M.Tech.',
   'age': 59,
   'title': 'MD, CEO & Director',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Samir  Seksaria',
   'title': 'Chief Financial Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Sukanya  Sadasivan B.E',
   'age': 55,
   'title': 'Senior VP & Chief Information Officer',
   'yearBorn': 1968,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kedar  Shirali',
   'title': 'Head of Global Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Madhav  Anchan',
   'title': 'General Counsel Legal',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Pradeep Manohar Gaitonde',
   'title': 'Company Secretary & Compliance Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Vivek  Padiyar',
   'title': 'Head of Corporate Communications',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Milind  Lakkad M.Tech.',
   'age': 59,
   'title': 'Chief Human Resources Officer',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Anita P. Nanadikar B.E',
   'age': 62,
   'title': 'Head of IOT & Incubation Group and VP',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 1,
 'boardRisk': 10,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 5,
 'overallRisk': 5,
 'governanceEpochDate': 1711670400,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 3876.3,
 'open': 3897.7,
 'dayLow': 3888.05,
 'dayHigh': 3933.3,
 'regularMarketPreviousClose': 3876.3,
 'regularMarketOpen': 3897.7,
 'regularMarketDayLow': 3888.05,
 'regularMarketDayHigh': 3933.3,
 'dividendRate': 51.0,
 'dividendYield': 0.013200001,
 'exDividendDate': 1705622400,
 'payoutRatio': 0.4075,
 'fiveYearAvgDividendYield': 1.28,
 'beta': 0.54,
 'trailingPE': 31.874594,
 'forwardPE': 27.74885,
 'volume': 1569333,
 'regularMarketVolume': 1569333,
 'averageVolume': 2504487,
 'averageVolume10days': 3894724,
 'averageDailyVolume10Day': 3894724,
 'marketCap': 14171154415616,
 'fiftyTwoWeekLow': 3070.25,
 'fiftyTwoWeekHigh': 4254.75,
 'priceToSalesTrailing12Months': 5.9338717,
 'fiftyDayAverage': 4018.818,
 'twoHundredDayAverage': 3635.5112,
 'trailingAnnualDividendRate': 51.0,
 'trailingAnnualDividendYield': 0.013156876,
 'currency': 'INR',
 'enterpriseValue': 13678062600192,
 'profitMargins': 0.18787001,
 'floatShares': 1003946924,
 'sharesOutstanding': 3618089984,
 'heldPercentInsiders': 0.72431,
 'heldPercentInstitutions': 0.15742,
 'impliedSharesOutstanding': 3649250048,
 'bookValue': 249.226,
 'priceToBook': 15.715655,
 'lastFiscalYearEnd': 1680220800,
 'nextFiscalYearEnd': 1711843200,
 'mostRecentQuarter': 1703980800,
 'earningsQuarterlyGrowth': 0.02,
 'netIncomeToCommon': 448660013056,
 'trailingEps': 122.88,
 'forwardEps': 141.15,
 'pegRatio': 3.93,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1527724800,
 'enterpriseToRevenue': 5.727,
 'enterpriseToEbitda': 22.324,
 '52WeekChange': 0.21134377,
 'SandP52WeekChange': 0.27393317,
 'lastDividendValue': 18.0,
 'lastDividendDate': 1705622400,
 'exchange': 'NSI',
 'quoteType': 'EQUITY',
 'symbol': 'TCS.NS',
 'underlyingSymbol': 'TCS.NS',
 'shortName': 'TATA CONSULTANCY S',
 'longName': 'Tata Consultancy Services Limited',
 'firstTradeDateEpochUtc': 1029123900,
 'timeZoneFullName': 'Asia/Kolkata',
 'timeZoneShortName': 'IST',
 'uuid': 'cc4c841e-ad42-3fdb-8d9f-b26fa8acd1cf',
 'messageBoardId': 'finmb_6411769',
 'gmtOffSetMilliseconds': 19800000,
 'currentPrice': 3916.75,
 'targetHighPrice': 4700.0,
 'targetLowPrice': 3011.0,
 'targetMeanPrice': 4014.3,
 'targetMedianPrice': 4040.0,
 'recommendationMean': 2.7,
 'recommendationKey': 'hold',
 'numberOfAnalystOpinions': 40,
 'totalCash': 430190002176,
 'totalCashPerShare': 118.9,
 'ebitda': 612719984640,
 'totalDebt': 75479998464,
 'quickRatio': 2.142,
 'currentRatio': 2.437,
 'totalRevenue': 2388180074496,
 'debtToEquity': 8.297,
 'revenuePerShare': 653.036,
 'returnOnAssets': 0.2387,
 'returnOnEquity': 0.45523998,
 'freeCashflow': 453116264448,
 'operatingCashflow': 437779988480,
 'earningsGrowth': 0.022,
 'revenueGrowth': 0.04,
 'grossMargins': 0.43014,
 'ebitdaMargins': 0.25656,
 'operatingMargins': 0.25015,
 'financialCurrency': 'INR',
 'trailingPegRatio': None}

In [7]:
stock.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m          0    0     0     0           0
1    -1m          1   11    25    10           2
2    -2m          2   11    21    11           2
3    -3m          2   11    21    12           2

In [8]:
tickers = ['META', 'AAPL', 'SPOT', 'PG']
for ticker in tickers:
    stock = yf.Ticker(ticker)
    print("Beta of {} is {}".format(ticker,stock.info['beta'] ))

Beta of META is 1.208
Beta of AAPL is 1.289
Beta of SPOT is 1.632
Beta of PG is 0.43

In [9]:
bitcoin = yf.Ticker('BTC-USD')
bitcoin.info

{'name': 'Bitcoin',
 'startDate': 1278979200,
 'description': 'Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,669,931. The last known price of Bitcoin is 69,652.92435432 USD and is down -1.13 over the last 24 hours. It is currently trading on 10945 active market(s) with $20,982,979,511.43 traded over the last 24 hours. More information can be found at https://bitcoin.org/.',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 71312.17,
 'open': 71312.17,
 'dayLow': 69220.8,
 'dayHigh': 71312.17,
 'regularMarketPreviousClose': 71312.17,
 'regularMarketOpen': 71312.17,
 'regularMarketDayLow': 69220.8,
 'regularMarketDayHigh': 71312.17,
 'volume': 26196887552,
 'regularMarketVolume': 26196887552,
 'averageVolume': 34433491338,
 'averageVolume10days': 33410074747,
 'averageDailyVolume10Day': 33410074747,
 'marketCap': 1366848307200,
 'fiftyTwoWeekLow': 24797.168,
 'fiftyTwoWeekHigh': 73750.07,
 'fiftyDayAverage': 61589.484,
 'twoHundredDayAverage': 43114.656,
 'currency': 'USD',
 'fromCurrency': 'BTC',
 'toCurrency': 'USD=X',
 'lastMarket': 'CoinMarketCap',
 'coinMarketCapLink': 'https://coinmarketcap.com/currencies/bitcoin',
 'volume24Hr': 26196887552,
 'volumeAllCurrencies': 26196887552,
 'circulatingSupply': 19670200,
 'exchange': 'CCC',
 'quoteType': 'CRYPTOCURRENCY',
 'symbol': 'BTC-USD',
 'underlyingSymbol': 'BTC-USD',
 'shortName': 'Bitcoin USD',
 'longName': 'Bitcoin USD',
 'firstTradeDateEpochUtc': 1410912000,
 'timeZoneFullName': 'UTC',
 'timeZoneShortName': 'UTC',
 'uuid': '74397779-1589-3270-8c45-b7f1a7345b3a',
 'messageBoardId': 'finmb_BTC_CCC',
 'trailingPegRatio': None}

In [10]:
# Let's import datetime package 
import datetime

stock = yf.Ticker("AAPL")
 
# Specify the starting date 
startDate = datetime.datetime(2022, 2, 20)
 
# Specify the end date 
endDate = datetime.datetime(2022, 2, 28)
 
# Obtain the stock price data
volume = stock.history(start = startDate, end = endDate)['Volume']

volume['2022-02-22 00:00:00-05:00']

91162800

# My R&D

In [4]:
# Let's import the library
import yfinance as yf 

# Pandas is used for dataframe and tabular data manipulation
import pandas as pd 

stock = yf.Ticker("HCLTECH.NS")
#print(stock.info)

#stock.recommendations
#dividends_splits_df = stock.actions
#dividends_splits_df


# Get the quarterly income statement (yearly=False to get quarterly data)
quarterly_income_statement = stock.get_income_statement(yearly=False)
quarterly_income_statement

AttributeError: 'Ticker' object has no attribute 'get_income_statement'